#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "http://localhost:4000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives
  - jekyll-multiple-languages-plugin

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

# jekyll-multiple-languages-plugin settings:
languages: ["en", "nl"
#  , "debug" #For testing multi-language
]

languages-names:
  en: English
  nl: Nederlands
  debug: Debug


exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
# default_locale_in_subfolder: true


#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: CodeGlass - Next Generation Profiler
# Website language
# lang: en-US //Managed by jekyll-multiple-languages-plugin

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Download Now
  url: https://github.com/CodeGlassDotIO/CodeGlassDotIO/releases

# Secondary Buttons
header-secondary-button:
  title: Discover More
  url: https://codeglassdotio.github.io/Docs

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: support@codeglass.io

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://codeglassdotio.github.io/Docs

####################################
######  Global Social Links   ######
####################################
#youtube: ""
#pinterest: ""
linkedin: " https://www.linkedin.com/company/codeglass"
facebook: "https://www.facebook.com/CodeGlassDotIO/"
twitter: "https://twitter.com/CodeGlassDotIO/"
github: "https://github.com/CodeGlassDotIO"
discord: "https://discord.gg/ytczAxSmX4"
#google-plus: "#"
#vimeo: "#"

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
# about-widget:
#   author-avatar: avatar-02.jpg
#   author-name: John Doe
#   author-tagline: Blog Author
#   author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
#   author-social-links:
#     youtube: "#"
#     pinterest: "#"
#     facebook: "#"
#     twitter: "#"
#     google-plus: "#"

# Google Map JS api
# key-api: YOUR_GOOGLE_MAP_API_KEY
# map-text: Sera Google Map
# map-lat: 44.4267674
# map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
# mailchimp:
#   user-id: REPLACEME
#   list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Theme created by Ohkimur
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

# footer-copyright-text: CodeGlass BV
# footer-copyright-url: https://codeglassdotio.github.io/Docs/contact
# footer-copyright-year: 2023
# footer-privcy-policy-url: https://codeglassdotio.github.io/Docs/docs/Legal/Privacy